window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){if(link.getAttribute('data-highlighted-by-user')!=='y')link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t796_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t796');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return!1;if(screenMax&&windowWidth>parseInt(screenMax,10))return!1;var shapeBorder=rec.querySelector('.t796__shape-border');var shapeRecId=container.getAttribute('data-shape-rec-ids');if(shapeRecId){shapeRecId=shapeRecId.split(',');for(var i=0;i<shapeRecId.length;i++){var shapeId=shapeRecId[i];var currentRec=document.querySelector('#rec'+shapeId);var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(currentRec,currentShape)}}else{var excludesBlocks=[215,316,390,651,702,706,708,750,756,766,825,862,868,943,945,674];var excludes='';for(var i=0;i<excludesBlocks.length;i++){excludes+=':not([data-record-type="'+excludesBlocks[i]+'"])'}
if(excludes.slice(-1)===','){excludes=excludes.slice(0,-1)}
var recs=[];if(shapeBorder.classList.contains('t796__shape-border_top')||shapeBorder.classList.contains('t796__shape-border_top-flip')){recs=t796__nextAll(rec,excludes)}
if(shapeBorder.classList.contains('t796__shape-border_bottom')||shapeBorder.classList.contains('t796__shape-border_bottom-flip')){recs=t796__prevAll(rec,excludes)}
if(recs.length!==0){var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(recs[0],currentShape)}}}
function t796_setColor(rec,shape){if(shape.getAttribute('data-fill-color'))return;var nearestBlock;if(shape.classList.contains('t796__shape-border_bottom')||shape.classList.contains('t796__shape-border_bottom-flip')){var nextBlock=rec.nextElementSibling;if(nextBlock){nearestBlock=nextBlock.matches('.r')?nextBlock:!1}}else{var prevBlock=rec.previousElementSibling;if(prevBlock){nearestBlock=prevBlock.matches('.r')?prevBlock:!1}}
if(!nearestBlock)return;var fillColor=nearestBlock.getAttribute('data-bg-color');if(!fillColor)return;var svg=shape.querySelector('.t796__svg');if(svg)svg.style.fill=fillColor}
function t796_addDivider(rec,shape){if(!rec)return;rec.setAttribute('data-animationappear','off');rec.classList.remove('r_hidden');var cover=rec.querySelector('.t-cover');var zeroBlock=rec.querySelector('.t396');if(cover||zeroBlock){if(cover){var showLayers=cover.querySelectorAll('.t557__snow-layer');if(showLayers.length>0)shape.style.zIndex=1;var coverFilter=cover.querySelector('.t-cover__filter');if(coverFilter)coverFilter.insertAdjacentElement('afterend',shape)}
if(zeroBlock){zeroBlock.insertAdjacentElement('afterend',shape);rec.style.position='relative';var zeroFilter=zeroBlock.querySelector('.t396__filter');if(zeroFilter){var zIndex=1;var zeroArtboard=zeroBlock.querySelector('.t396__artboard');var isVisible=getComputedStyle(zeroArtboard,null).overflow==='visible';if(!isVisible)zIndex=99;shape.style.zIndex=zIndex}}
shape.style.display='block'}else{var wrapper=rec;var recordType=parseInt(rec.getAttribute('data-record-type'));if(!wrapper)return!0;wrapper.appendChild(shape);wrapper.style.position='relative';var excludesBlocks=[125,331,554,746,754,776,778,786,858,896,897,924,915,943,945,951,1004,1025];if(excludesBlocks.indexOf(recordType)===-1){var notZIndexBlocks=[983];var firstDiv=wrapper.querySelector('div');firstDiv.style.position='relative';firstDiv.classList.add('t796_cont-near-shape-divider');if(notZIndexBlocks.indexOf(recordType)!==-1){firstDiv.style.zIndex=0}else{firstDiv.style.zIndex='1'}}
var blocks=[195,246,279,675,694,734,823,938];if(blocks.indexOf(recordType)!==-1){shape.style.zIndex=1}
shape.style.display='block'}}
function t796__nextAll(element,selector){var nextElements=[];var nextElement=element;while(nextElement.nextElementSibling){nextElement=nextElement.nextElementSibling;if(nextElement.id==='t-footer'){var footerElements=nextElement.querySelectorAll('.r');if(footerElements.length!==0){nextElement=footerElements[0];if(nextElement.matches(selector)){nextElements.push(nextElement)}
nextElements=nextElements.concat(t796__nextAll(nextElement,selector))}}else if(nextElement.matches(selector)){nextElements.push(nextElement)}}
return nextElements}
function t796__prevAll(element,selector){var prevElements=[];var prevElement=element;while(prevElement.previousElementSibling){prevElement=prevElement.previousElementSibling;if(prevElement.id==='t-header'){var headerElements=prevElement.querySelectorAll('.r');if(headerElements.length!==0){prevElement=headerElements[headerElements.length-1];if(prevElement.matches(selector)){prevElements.push(prevElement)}
prevElements=prevElements.concat(t796__prevAll(prevElement,selector))}}else if(prevElement.matches(selector)){prevElements.push(prevElement)}}
return prevElements}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
function t833_init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapper=rec.querySelector('.t833__sliderwrapper');if(!wrapper)return;var dataContainer=rec.querySelector('.t833');if(!dataContainer)return;var coverRecs=dataContainer.getAttribute('data-coverslider-rec-ids');t833_showOnCertainWidth(rec,wrapper);if(document.querySelector('#allrecords').getAttribute('data-tilda-mode')==='edit'){var recDemo=rec.querySelector('.t833__demo');t833_addAnimation(recDemo,wrapper);return}
if(coverRecs){coverRecs=coverRecs.split(',');Array.prototype.forEach.call(coverRecs,function(rec){var currentRec=document.querySelector('#rec'+rec);var currentWrapper=wrapper.cloneNode(!0);currentWrapper.style.position='absolute';if(currentRec){t833_addAnimation(currentRec,currentWrapper)}})}else{var nextBlock=rec.nextElementSibling;var prevBlock=rec.previousElementSibling;var currentWrapper=wrapper.cloneNode(!0);currentWrapper.style.position='absolute';if(nextBlock&&nextBlock.querySelector('.t-cover')){t833_addAnimation(nextBlock,currentWrapper)}else if(prevBlock&&prevBlock.querySelector('.t-cover')){t833_addAnimation(prevBlock,currentWrapper)}}}
function t833_showOnCertainWidth(rec,wrapper){currentClass=rec.getAttribute('class');classListArr=currentClass.split(' ');Array.prototype.forEach.call(classListArr,function(classItem){if(classItem.indexOf('t-screen')!==-1){wrapper.classList.add(classItem)}})}
function t833_addAnimation(currentRec,wrapper){if(!currentRec)return;currentRec.setAttribute('data-animationappear','off');currentRec.classList.remove('r_hidden');var currentRecType=currentRec.getAttribute('data-record-type');var isT941=currentRecType==='941';var isT996=currentRecType==='996';if(currentRecType==='396'){currentRec.querySelector('.t396__filter').insertAdjacentElement('afterend',wrapper);wrapper.style.zIndex='0'}
var coverWrapper;if(isT941){coverWrapper=currentRec.querySelector('.t941__cover-wrap')}else if(isT996){coverWrapper=currentRec.querySelector('.t996__cover-wrapper')}else{coverWrapper=currentRec.querySelector('.t-cover')}
if(coverWrapper){if(isT941){wrapper.classList.add('t941__cover');coverWrapper.appendChild(wrapper)}else if(isT996){wrapper.classList.add('t996__cover');coverWrapper.appendChild(wrapper)}else{coverWrapper.querySelector('.t-cover__filter').insertAdjacentElement('afterend',wrapper)}
wrapper.style.zIndex='0'}
var images=t833_createImageArr(wrapper);var imageCount=images.length;var imagesLoaded=0;for(var i=0;i<imageCount;i++){images[i].onload=function(){imagesLoaded++;if(imagesLoaded==imageCount&&currentRec.length!==0){setTimeout(function(){t833_changeSlide(currentRec)},3000)}}}
var slider=currentRec.querySelector('.t833__slider');var allSlides=currentRec.querySelectorAll('.t833__slide');var numberOfSlides=allSlides.length;if(numberOfSlides===3||numberOfSlides===2){Array.prototype.forEach.call(allSlides,function(slide){var cloneSlide=slide.cloneNode(!0);slider.appendChild(cloneSlide)})}}
function t833_createImageArr(wrapper){var imagesSrc=[];allSlides=wrapper.querySelectorAll('.t833__slide');Array.prototype.forEach.call(allSlides,function(slideItem){imagesSrc.push(slideItem.getAttribute('data-original'))});var images=[];Array.prototype.forEach.call(imagesSrc,function(image,i){images[i]=new Image();images[i].src=image});return images}
function t833_changeSlide(currentRec){var sliderWrapper=currentRec.querySelectorAll('.t833__sliderwrapper');Array.prototype.forEach.call(sliderWrapper,function(sliderItem){var isLoaded=sliderItem.getAttribute('data-loaded')&&sliderItem.getAttribute('data-loaded')==='yes'?!0:!1;if(!isLoaded){var slides=sliderItem.querySelectorAll('.t833__slide');var firstSlide=sliderItem.querySelector('.t833__slide:first-child');var numberOfSlides=slides.length;firstSlide.classList.add('t833__slide_fx1');setTimeout(function(){t833_kenBurns(slides,numberOfSlides,1)},500);sliderItem.setAttribute('data-loaded','yes')}});function t833_kenBurns(slides,numberOfSlides,i){if(i==numberOfSlides)i=0;slides[i].classList.add('t833__slide_fx');if(i===0&&slides[numberOfSlides-2]){slides[numberOfSlides-2].classList.remove('t833__slide_fx');slides[numberOfSlides-2].classList.remove('t833__slide_fx1')}
if(i===1&&slides[numberOfSlides-1]){slides[numberOfSlides-1].classList.remove('t833__slide_fx');slides[numberOfSlides-1].classList.remove('t833__slide_fx1');Array.prototype.forEach.call(slides,function(slide){slide.classList.remove('t833__slide_opacity')})}
if(i>1&&slides[i-2]){slides[i-2].classList.remove('t833__slide_fx');slides[i-2].classList.remove('t833__slide_fx1')}
setTimeout(function(){t833_kenBurns(slides,numberOfSlides,i+1)},5000)}}
function t604_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);window.addEventListener('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));if(typeof jQuery!=='undefined'){$(rec).find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}else{var currentBlock=rec.querySelector('.t604');if(currentBlock){currentBlock.addEventListener('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}}}
function t604_show(recid){var rec=document.getElementById('rec'+recid);var playBtns=rec.querySelectorAll('.t604__play');Array.prototype.forEach.call(playBtns,function(play){play.addEventListener('click',function(){var parent=play.parentElement;var videoBg=parent?parent.querySelector('.t-slds__bgimg'):null;if(videoBg)videoBg.style.opacity='0';var sliderVideo=play.getAttribute('data-slider-video-type');var url=play.getAttribute('data-slider-video-url');var nextEl=play.nextElementSibling;if(nextEl)nextEl.style.zIndex='3';var iframe;switch(sliderVideo){case 'youtube':iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://www.youtube.com/embed/'+url+'?autoplay=1&enablejsapi=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');iframe.setAttribute('allow','autoplay');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break;case 'vimeo':var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(url);var id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;iframe=document.createElement('iframe');iframe.classList.add('t604__iframe');iframe.width='100%';iframe.height='100%';iframe.src='https://player.vimeo.com/video/'+id+hash+'?autoplay=1&amp;api=1';iframe.frameBorder='0';iframe.setAttribute('webkitallowfullscreen','');iframe.setAttribute('mozallowfullscreen','');iframe.setAttribute('allowfullscreen','');if(nextEl)nextEl.innerHTML='';if(nextEl)nextEl.appendChild(iframe);break}})})}
function t604_hide(recid){var rec=document.getElementById('rec'+recid);var frames=rec.querySelectorAll('.t604__frame');rec.addEventListener('updateSlider',function(){Array.prototype.forEach.call(frames,function(frame){frame.innerHTML='';frame.style.zIndex=''})})}
function t604_imageHeight(recid){var rec=document.getElementById('rec'+recid);var images=rec.querySelectorAll('.t604__separator');Array.prototype.forEach.call(images,function(image){var imgHeight=image.getAttribute('data-slider-image-height');var imgWidth=image.getAttribute('data-slider-image-width');var imgRatio=imgHeight/imgWidth;var imgPadding=imgRatio*100;image.style.paddingBottom=imgPadding+'%'})}
function t604_arrowWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var arrows=rec.querySelectorAll('.t-slds__arrow_wrapper');var slide=rec.querySelector('.t-slds__wrapper');var slideWidth=slide?slide.offsetWidth:0;if(slide&&slideWidth===0){t_onFuncLoad('t_slds_SliderWidth',function(){setTimeout(function(){slideWidth=slide.offsetWidth;t604__updateArrowWidth(slideWidth,arrows)},300)})}else{t604__updateArrowWidth(slideWidth,arrows)}}
function t604__updateArrowWidth(slideWidth,arrows){var calcArrowWidth=window.innerWidth-slideWidth;var arrowWidth=window.innerWidth>960?(calcArrowWidth/2)+'px':'';if(arrowWidth!=='0px'&&arrowWidth!==''){Array.prototype.forEach.call(arrows,function(arrow){arrow.style.width=arrowWidth})}}
function t604__UpdateSliderArrowsHeight(recid){var sliderRec=document.getElementById('rec'+recid);if(!sliderRec)return;var activeItem=sliderRec.querySelector('.t-slds__item_active');if(activeItem){var separator=activeItem.querySelector('.t604__separator');var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);var offsetForVideoBtns=0;var isVideo=activeItem.querySelector('[data-slider-video-type]');if(isVideo&&isMobile)offsetForVideoBtns=40;var itemPaddingTop=parseInt(getComputedStyle(activeItem).paddingTop)||0;var itemPaddingBottom=parseInt(getComputedStyle(activeItem).paddingBottom)||0;var height=(itemPaddingTop+itemPaddingBottom)-offsetForVideoBtns;if(separator&&separator.hasAttribute('data-slider-image-height')&&activeItem.clientHeight===0){height=parseInt(separator.getAttribute('data-slider-image-height'))-height}else{height=activeItem.clientHeight-height}}
var arrowWrappers=sliderRec.querySelectorAll('.t-slds__arrow_wrapper');if(height&&arrowWrappers.length>0){Array.prototype.forEach.call(arrowWrappers,function(arrowWrapper){arrowWrapper.style.height=height+'px';var arrow=arrowWrapper.querySelector('.t-slds__arrow');if(arrow)arrow.style.marginTop=offsetForVideoBtns/2+'px'})}}
function t1093__init(recID){var rec=document.getElementById('rec'+recID);if(!rec)return;var popup=rec.querySelector('.t-popup');if(!popup)return;t1093__processGlobalObj();t1093__updateGlobalObj('popupList',popup,'array');t1093__processPopupClassList(popup);var popupContainer=popup.querySelector('.t-popup__container');if(!popupContainer)return;var blockList=popup.getAttribute('data-popup-rec-ids');blockList=blockList.split(',');blockList.forEach(function(blockID){var blockRec=document.getElementById('rec'+blockID);if(!blockRec)return;var recordType=blockRec.getAttribute('data-record-type');if(recordType!=='396'&&recordType!=='121')return;popupContainer.appendChild(blockRec);t1093__setPointerEventsToZeroBlock(blockRec);t_onFuncLoad('t396_init',function(){t396_init(blockID)})});var currentEvent=t1093__getGlobalObjValue('isMobile')?'orientationchange':'resize';window.removeEventListener(currentEvent,t1093__resizeAllPopups);window.addEventListener(currentEvent,t1093__resizeAllPopups);t1093__processScrollablePopup(popup)}
function t1093__processGlobalObj(){if(typeof window.t1093_popupList==='undefined')window.t1093_popupList=[];if(typeof window.t1093_resizeTimer==='undefined')window.t1093_resizeTimer=0;if(typeof window.t1093_hoverTimer==='undefined')window.t1093_hoverTimer=0;if(typeof window.t1093_activeHoverHook==='undefined')window.t1093_activeHoverHook='';if(typeof window.t1093_isMobile==='undefined'){window.t1093_isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)||('ontouchend' in document&&navigator.userAgent.indexOf('AppleWebKit')!==-1)}
if(typeof window.t1093_windowWidth==='undefined')window.t1093_windowWidth=t1093__getWindowWidth();if(typeof window.t1093_isMobRes==='undefined')window.t1093_isMobRes=window.t1093_windowWidth<980;if(typeof window.t1093_isSafari==='undefined'){window.t1093_isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent)}}
function t1093__processScrollablePopup(popup){if(!popup)return;var popupContainer=popup.querySelector('.t-popup__container');if(!popupContainer)return;popup.style.display='block';var popupHeight=popupContainer.offsetHeight;popup.style.display='';var windowHeight=window.t1093_isMobile?document.documentElement.clientHeight:window.innerHeight;if(popupHeight>windowHeight){popupContainer.classList.add('t-popup__container-static')}}
function t1093__updateGlobalObj(key,value,type){switch(type){case 'array':window['t1093_'+key].push(value);break;case 'boolean':window['t1093_'+key]=value;break;case 'string':window['t1093_'+key]=value||'';break;case 'timeout':if(window['t1093_'+key])clearTimeout(window['t1093_'+key]);window['t1093_'+key]=value;break}}
function t1093__getGlobalObjValue(key){return window['t1093_'+key]}
function t1093__getWindowWidth(){return t1093__getGlobalObjValue('isMobile')?document.documentElement.clientWidth:window.innerWidth}
function t1093__resizeAllPopups(){var newTimeout=setTimeout(function(){var currentWindowWidth=t1093__getWindowWidth();var isMobile=currentWindowWidth<980;var isMobileResolution=t1093__getGlobalObjValue('isMobRes');if(isMobile===isMobileResolution)return;t1093__updateGlobalObj('isMobRes',isMobile,'boolean');t1093__getGlobalObjValue('popupList').forEach(function(popup){t1093__processPopupClassList(popup)});t1093__updateGlobalObj('resizeTimer',0,'timeout')},500);t1093__updateGlobalObj('resizeTimer',newTimeout,'timeout')}
function t1093__processPopupClassList(popup){t1093__clearPopupClassList(popup);var popupClassList=[];var safariDesktopClassName='t-popup-safari';var isMobileResolution=t1093__getGlobalObjValue('isMobRes');var isSafari=t1093__getGlobalObjValue('isSafari');if(!isMobileResolution&&isSafari&&!popup.classList.contains(safariDesktopClassName)){popupClassList.push(safariDesktopClassName)}
var animAttr='data-anim';var mobileAttr=animAttr+'-mobile';var attrValue=popup.getAttribute(animAttr);if(isMobileResolution){var mobileAttrValue=popup.getAttribute(mobileAttr);if(mobileAttrValue)attrValue=mobileAttrValue}
if((isMobileResolution&&attrValue!=='empty')||(!isMobileResolution&&attrValue)){popupClassList.push('t-popup-anim-'+attrValue);popupClassList.push('t-popup-transition')}
popupClassList.forEach(function(className){popup.classList.add(className)})}
function t1093__clearPopupClassList(popup){popup.classList.remove('t-popup-transition');for(var key=0;key<popup.classList.length;key++){var className=popup.classList[key];if(className.indexOf('t-popup-anim-')!==-1)popup.classList.remove(className)}}
function t1093__setPointerEventsToZeroBlock(rec){var artBoard=rec.querySelector('.t396__artboard');if(!artBoard)return;var abFilter=artBoard.querySelector('.t396__filter');var artBoardStyle=getComputedStyle(artBoard);var abFilterBG=abFilter?getComputedStyle(abFilter).backgroundImage:'';var hasBG=abFilterBG!=='none'||artBoardStyle.backgroundColor!=='rgba(0, 0, 0, 0)'||artBoardStyle.backgroundImage!=='none';if(hasBG)artBoard.classList.add('t396__artboard_pointer-events-auto')}
function t1093__initPopup(recID){var rec=document.getElementById('rec'+recID);if(!rec)return;rec.setAttribute('data-animationappear','off');rec.style.opacity='1';var popup=rec.querySelector('.t-popup');var hook=popup.getAttribute('data-tooltip-hook');if(!popup||!hook)return;t1093__generatePopupObj();t1093__updatePopupObjValue('hookList',hook);var isMobile=t1093__getGlobalObjValue('isMobile');var isHoverTrigger=t1093__getBooleanPopupAttribute(popup,'hover-trigger')&&!isMobile;if(isHoverTrigger){t1093__updatePopupObjValue('hoverHookList',hook);popup.classList.add('t-popup_hover-trigger')}
t1093__setListenersForPopup(popup,isHoverTrigger);t1093__setListenersForDocument(isHoverTrigger);t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,hook)});t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(hook)});if(!isHoverTrigger)t1093__setAnalyticsListeners(popup);if(t1093__getBooleanPopupAttribute(popup,'open-on-page-load')){t1093__onReady(function(){setTimeout(function(){t1093__showCurrentPopup(popup)},1000)})}}
function t1093__onReady(callback){document.readyState!=='loading'?callback():document.addEventListener('DOMContentLoaded',callback)}
function t1093__generatePopupObj(){if(window.tPopupObj)return;window.tPopupObj={hookList:[],hoverHookList:[],openPopUpList:[],}}
function t1093__updatePopupObjValue(key,value){if(!window.tPopupObj||!window.tPopupObj[key])return;if(window.tPopupObj[key].indexOf(value)===-1)window.tPopupObj[key].push(value)}
function t1093__getPopupObjValue(key){return window.tPopupObj[key]}
function t1093__showOnHover(e){var popup=e.target.closest('.t-popup');if(!popup)e.preventDefault();if(popup&&!popup.classList.contains('t-popup_show'))return;t1093__updateGlobalObj('hoverTimer',0,'timeout');var targetHook=t1093__getHookOnHover(e);var activeHoverHook=t1093__getGlobalObjValue('activeHoverHook');if(targetHook&&targetHook===activeHoverHook)return;t1093__closePopup(!0,-1,!1);t1093__updateGlobalObj('activeHoverHook',targetHook,'string');t1093__processCurrentPopupOnShow(targetHook)}
function t1093__hideOnHover(e){var targetHook=t1093__getHookOnHover(e);var newTimeout=setTimeout(function(){t1093__updateGlobalObj('activeHoverHook','','string');var openPopupList=t1093__getPopupObjValue('openPopUpList');var openPopupIndex=openPopupList.indexOf(targetHook);if(openPopupIndex!==-1){t1093__closePopup(!1,openPopupIndex,!1)}
t1093__updateGlobalObj('hoverTimer',0,'timeout')},300);t1093__updateGlobalObj('hoverTimer',newTimeout,'timeout')}
function t1093__getHookOnHover(e){var target=e.target;var popupTarget=target.closest('.t-popup');return(popupTarget?popupTarget.getAttribute('data-tooltip-hook'):target.getAttribute('href'))||''}
function t1093__showOnClick(e){var hookList=t1093__getPopupObjValue('hookList');if(!hookList.length)return;var target=e.target;var hookListSelector=t1093__createSelectorFromHookList(!1);var targetLink=target.closest(hookListSelector);if(!targetLink)return;e.preventDefault();var targetHook=targetLink.getAttribute('href')||'';var openPopupList=t1093__getPopupObjValue('openPopUpList');var openPopupIndex=openPopupList.indexOf(targetHook);if(openPopupIndex!==-1&&e.isTrusted){t1093__closePopup(!1,openPopupIndex,!1);return}
t1093__processCurrentPopupOnShow(targetHook)}
function t1093__processCurrentPopupOnShow(targetHook){var currentPopup=document.querySelector('[data-tooltip-hook="'+targetHook+'"]');var currentPopupRec=currentPopup?currentPopup.closest('.r'):null;t1093__showCurrentPopup(currentPopup);if(currentPopupRec){t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(currentPopupRec.id.replace('rec',''))})}
var isScrollablePopup=currentPopup.querySelector('.t-popup__container-static');var isPopupHasDisabledBG=t1093__getBooleanPopupAttribute(currentPopup,'disabled-bg');var isPopupHasLockScroll=t1093__getBooleanPopupAttribute(currentPopup,'disable-lock-scroll');if(isScrollablePopup){if(isPopupHasLockScroll)t1093__updateBodyOnAction('add');if(isPopupHasDisabledBG)currentPopup.classList.remove('t-popup-disabled-bg')}else{if(isPopupHasDisabledBG)currentPopup.classList.add('t-popup-disabled-bg')}}
function t1093__getBooleanPopupAttribute(popup,attrName){return popup.getAttribute('data-popup-'+attrName)==='y'}
function t1093__createSelectorFromHookList(isHoverTrigger){var hookListName=isHoverTrigger?'hoverHookList':'hookList';var hookList=t1093__getPopupObjValue(hookListName);var selectorList=hookList.map(function(hook){return 'a[href="'+hook+'"]'});return selectorList.join(', ')}
function t1093__setListenersForPopup(popup,isHoverTrigger){if(!popup)return;if(isHoverTrigger){t1093__processEventsOnHover(popup)}else{popup.removeEventListener('click',t1093__closePopupOnClick);popup.addEventListener('click',t1093__closePopupOnClick)}}
function t1093__setListenersForDocument(isHoverTrigger){if(isHoverTrigger){var selectorList=t1093__createSelectorFromHookList(isHoverTrigger);var hookLinks=Array.prototype.slice.call(document.querySelectorAll(selectorList));hookLinks.forEach(function(link){t1093__processEventsOnHover(link)})}else{document.removeEventListener('click',t1093__showOnClick);document.addEventListener('click',t1093__showOnClick)}
document.removeEventListener('click',t1093__processCloseLink);document.removeEventListener('keydown',t1093__closeOnESC);document.addEventListener('keydown',t1093__closeOnESC);document.addEventListener('click',t1093__processCloseLink)}
function t1093__setAnalyticsListeners(popup){var popupAnalytics=popup.getAttribute('data-track-popup');if(!popupAnalytics)return;var currentHook=popup.getAttribute('data-tooltip-hook');document.addEventListener('click',function(e){var hookLink=e.target.closest('a[href="'+currentHook+'"]');if(!hookLink)return;if(window.Tilda)Tilda.sendEventToStatistics(popupAnalytics,currentHook)})}
function t1093__processEventsOnHover(elem){elem.removeEventListener('mouseover',t1093__showOnHover);elem.removeEventListener('mouseout',t1093__hideOnHover);elem.addEventListener('mouseover',t1093__showOnHover);elem.addEventListener('mouseout',t1093__hideOnHover)}
function t1093__closeOnESC(e){if(e.keyCode===27){e.preventDefault();t1093__closePopup(!1,-1,!0)}}
function t1093__processCloseLink(e){var isCloseLink=e.target.closest('a[href="#closepopup"]');var isAllCloseLink=e.target.closest('a[href="#closeallpopup"]');if(!isCloseLink&&!isAllCloseLink)return;e.preventDefault();t1093__closePopup(Boolean(isAllCloseLink),-1,!0)}
function t1093__closeOnLink(e){var openPopupList=t1093__getPopupObjValue('openPopUpList');if(!openPopupList.length)return;var popupLink=e.target.closest('a[href*="#"]');if(!popupLink)return;var exceptionSelectors=['.t978__tm-link','.t966__tm-link','.t794__tm-link','a[href="#closepopup"]','a[href="#closeallpopup"]',];var isLinkHasSubmenu=exceptionSelectors.some(function(selector){return popupLink.closest(selector)});if(!isLinkHasSubmenu)t1093__closePopup(!0,-1,!0)}
function t1093__closePopupOnClick(e){var isCloseButton=e.target.closest('.t-popup__close');var isPopupBackground=!e.target.closest('.t-popup__container');if(isPopupBackground){var currentPopup=e.target.closest('.t-popup');var currentPopupHook=currentPopup?currentPopup.getAttribute('data-tooltip-hook'):'';var openPopupList=t1093__getPopupObjValue('openPopUpList');var currentPopupIndex=openPopupList.indexOf(currentPopupHook);t1093__closePopup(!1,currentPopupIndex,!0)}
if(isCloseButton)t1093__closePopup(!1,-1,!0)}
function t1093__showCurrentPopup(popup){if(!popup)return;if(popup.closeTimerID)clearTimeout(popup.closeTimerID);var rec=popup.closest('.r');var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popupHook=popup.getAttribute('data-tooltip-hook');t1093__updatePopupObjValue('openPopUpList',popupHook);document.removeEventListener('click',t1093__closeOnLink);document.addEventListener('click',t1093__closeOnLink);popup.style.display='block';var popupBG=popup.nextElementSibling;if(popupBG)popupBG.classList.add('t-popup__bg-active');var allRecords=document.getElementById('allrecords');var isLazy=allRecords?allRecords.getAttribute('data-tilda-lazy')==='yes':!1;if(window.lazy==='y'||isLazy){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
var artBoard=popup.querySelector('.t396__artboard');if(artBoard&&!popup.resizeProcessed){var blockID=artBoard.getAttribute('data-artboard-recid')||'';t_onFuncLoad('t396_doResize',function(){t396_doResize(blockID);popup.resizeProcessed=!0})}
var galleryElems=Array.prototype.slice.call(popup.querySelectorAll('[data-elem-type="gallery"]'));if(galleryElems.length){t_onFuncLoad('t_slds_updateSlider',function(){galleryElems.forEach(function(element){t_slds_updateSlider([element])})})}
var formElems=Array.prototype.slice.call(popup.querySelectorAll('[data-elem-type="form"]'));formElems.forEach(function(elem){var form=elem.querySelector('.t-form');if(!form)return;form.removeAttribute('data-success-popup')});setTimeout(function(){popup.focus();var popupContainer=popup.querySelector('.t-popup__container');if(popupContainer)popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t_onFuncLoad('t_popup__trapFocus',function(){t_popup__trapFocus(popup)})},50);var popupTimer=t1093__getTimer(popup,'open');var needFadeOut=t1093__getResponsiveAttr(popup,'anim-close')==='fadein';if(needFadeOut){popup.openTimerID=setTimeout(function(){popup.classList.add('t-popup-fadeout');popup.openTimerID=0},popupTimer)}
if((popupTimer&&window.lazy==='y')||isLazy){setTimeout(function(){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})},popupTimer)}
if(!t1093__getBooleanPopupAttribute(popup,'disable-lock-scroll')){t1093__updateBodyOnAction('add')}}
function t1093__closePopup(closeAll,index,removeAnimOnCloseFromHook){var openPopupList=t1093__getPopupObjValue('openPopUpList');if(!openPopupList.length)return;var popupList=t1093__processClosedPopupList(closeAll,index);if(!popupList.length)return;openPopupList=t1093__getPopupObjValue('openPopUpList');var isLastPopup=openPopupList.length===0;popupList.forEach(function(popup){if(isLastPopup)t1093__updateBodyOnAction('remove');popup.classList.remove('t-popup_show');if(popup.openTimerID)clearTimeout(popup.openTimerID);t1093__removeAnimationOnClose(popup);if(removeAnimOnCloseFromHook)t1093__removeAnimFromHookLinkOnClose(popup);t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});var popupCloseTimer=t1093__getTimer(popup,'close');popup.closeTimerID=setTimeout(function(){if(!popup.classList.contains('t-popup_show'))popup.style.display='none';var popupBG=popup.nextElementSibling;if(popupBG)popupBG.classList.remove('t-popup__bg-active');popup.classList.remove('t-popup-fadeout');t1093__pauseAllVideo(popup);popup.closeTimerID=0},popupCloseTimer)})}
function t1093__updateBodyOnAction(action){var triggeredEvent=action==='add'?'popupShowed':'popupHidden';var body=document.body;if(typeof t_triggerEvent==='function')t_triggerEvent(body,triggeredEvent);body.classList[action]('t-body_popupshowed')}
function t1093__pauseAllVideo(popup){if(!popup)return;var videoElems=Array.prototype.slice.call(popup.querySelectorAll('[data-elem-type="video"], [data-elem-type="gallery"]'));videoElems.forEach(function(element){var videoElem=element.querySelector('video, iframe');if(!videoElem)return;if(videoElem.tagName==='VIDEO')videoElem.pause();if(videoElem.tagName!=='IFRAME'||!videoElem.src)return;if(videoElem.src.indexOf('&enablejsapi=1')!==-1){videoElem.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}','*')}
if(videoElem.src.indexOf('vimeo')!==-1&&videoElem.src.indexOf('&api=1')!==-1){videoElem.contentWindow.postMessage('{"method":"pause","value":"true"}','*')}})}
function t1093__getTimer(popup,action){var isMobileResolution=t1093__getGlobalObjValue('isMobRes');if(typeof isMobileResolution==='undefined')return 50;var isZeroTimer=t1093__getResponsiveAttr(popup,'anim-close')==='empty';if((isZeroTimer&&action==='close')||!popup.classList.contains('t-popup-transition'))return 0;var popupTimer=popup.getAttribute('data-anim-timeout');if(popupTimer)popupTimer*=1000;return popupTimer||0}
function t1093__getResponsiveAttr(popup,attr){var isMobileResolution=t1093__getGlobalObjValue('isMobRes');if(typeof isMobileResolution==='undefined')return null;var currentAttr='data-'+attr;if(isMobileResolution){var attrMob=popup.getAttribute(currentAttr+'-mobile');if(attrMob)return attrMob}
return popup.getAttribute(currentAttr)}
function t1093__removeAnimFromHookLinkOnClose(popup){var popupHook=popup.getAttribute('data-tooltip-hook');var popupInitLinks=Array.prototype.slice.call(document.querySelectorAll('a[href="'+popupHook+'"]'));popupInitLinks.forEach(function(link){var animEl=link.closest('.js-sbs-anim-trigger_click');if(!animEl)return;var animElID=animEl.getAttribute('data-elem-id');var animElArtBoard=animEl.closest('.t396__artboard');var alreadyAnimatedEls=Array.prototype.slice.call(animElArtBoard.querySelectorAll('.t-sbs-anim_started'));alreadyAnimatedEls.forEach(function(animEl){var triggersList=animEl.getAttribute('data-animate-sbs-trgels');if(!triggersList||triggersList.indexOf(animElID)===-1)return;animEl.classList.remove('t-sbs-anim_started')})})}
function t1093__processClosedPopupList(closeAll,index){var openPopupList=t1093__getPopupObjValue('openPopUpList');var hookList=closeAll?openPopupList:openPopupList.slice(index);var popupSelectors=hookList.map(function(hook){return '[data-tooltip-hook="'+hook+'"]'});popupSelectors=popupSelectors.join(', ');t1093__clearPopupObjKey('openPopUpList',closeAll,index);return Array.prototype.slice.call(document.querySelectorAll(popupSelectors))}
function t1093__removeAnimationOnClose(popup){var popupAnimElems=Array.prototype.slice.call(popup.querySelectorAll('.t-animate_started'));var windowWidth=(window.tn&&window.tn.curResolution)||window.innerWidth;popupAnimElems.forEach(function(elem){if(windowWidth<1200&&elem.getAttribute('data-animate-mobile')!=='y')return;elem.classList.remove('t-animate_started');elem.classList.add('t-animate_wait')})}
function t1093__clearPopupObjKey(key,emptyAll,index){if(!window.tPopupObj||!window.tPopupObj[key])return;if(emptyAll){window.tPopupObj[key]=[]}else{if(index===-1){window.tPopupObj[key].pop()}else{window.tPopupObj[key]=window.tPopupObj[key].slice(0,index)}}}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var windowOffset=offset||window.innerHeight;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);rec.addEventListener('click',function(e){if(e.target.closest('.t890__arrow')){isSafari?t890__animateScrollPolyfill(0):t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
window.requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)}})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){if(document.body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var body=document.body;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth');if(window.isMobile&&canSmoothScroll&&'scrollBehavior' in document.documentElement.style){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth'});setTimeout(function(){body.removeAttribute('data-scroll')},500)}else{var html=document.querySelector('html');var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);var scrollY=window.scrollY||document.documentElement.scrollTop;var speed=2000;var time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8));var currentTime=0;function t270_easeInQuad(pos){return Math.pow(pos,2)}
function t270_animationScroll(){currentTime+=1/60;var newDocumentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);if(documentHeight<newDocumentHeight){documentHeight=newDocumentHeight;scrollTargetY=t270_getTarget(hash,offset);scrollY=window.scrollY||document.documentElement.scrollTop;time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8))}
var difference=currentTime/time;var animation=t270_easeInQuad(difference);if(difference<1){requestAnimationFrame(t270_animationScroll);window.scrollTo(0,scrollY+((scrollTargetY-scrollY)*animation))}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,scrollTargetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');t270_animationScroll()}}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt((target.getBoundingClientRect().top+window.pageYOffset)-offset,10);target=Math.max(target,0);return target}